//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace map2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("map2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τσεχία-Μικρή Πόλη-Το πιο γραφικό σημείο μιας γραφικής πόλης!Την περιοχή της Μικρής Πόλης την διαπερνάει σαν άξονας ένα τμήμα της λεγόμενης &quot;βασιλικής οδού&quot;, που αφού συναντηθεί με την Γέφυρα του Καρόλου, συνεχίζει γύρω από την μπαρόκ Εκκλησία του Αγ. Νικολάου και ανεβαίνει την υπέροχη οδό Νερούντοβα, πριν τη μεγάλη στροφή προς το Κάστρο. Όμως πολλές από τις ομορφιές αυτής της συνοικίας βρίσκονται μακριά από αυτό τον άξονα, που ακολουθούν οι περισσότεροι επισκέπτες.... Στους παρακάτω ήσυχους δρόμους, στο νη [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ch {
            get {
                return ResourceManager.GetString("ch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ch1 {
            get {
                object obj = ResourceManager.GetObject("ch1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ch2 {
            get {
                object obj = ResourceManager.GetObject("ch2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ch3 {
            get {
                object obj = ResourceManager.GetObject("ch3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ch4 {
            get {
                object obj = ResourceManager.GetObject("ch4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Γαλλία-Ο πυργος του Αϊφελ-
        ///Είναι το σήμα κατατεθέν της πόλης του Παρισιού. Κατασκευάστηκε το 1889 από τον μηχανικό Γουστάβο Άιφελ και σήμερα αποτελεί ένα από τα γνωστότερα κτίρια στον κόσμο. Με ύψος 324 μέτρα (300 χωρίς την κεραία) ήταν το πιο ψηλό κτίριο στον κόσμο μέχρι που το ξεπέρασε το Εμπάιρ Στέιτ Μπίλντινγκ της Νέας Υόρκης το 1931.
        ///-Το μουσείο του Λούβρου -
        ///Το μουσείο του Λούβρου (γαλλικά: Musée du Louvre) είναι ένα από τα μεγαλύτερα και παλαιότερα μουσεία τέχνης στον κόσμο. Βρίσκεται στο κέντρο τ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fra {
            get {
                return ResourceManager.GetString("fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fra1 {
            get {
                object obj = ResourceManager.GetObject("fra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fra2 {
            get {
                object obj = ResourceManager.GetObject("fra2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fra3 {
            get {
                object obj = ResourceManager.GetObject("fra3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fra4 {
            get {
                object obj = ResourceManager.GetObject("fra4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αγγλία
        ///- Big Ben -
        ///Μπιγκ Μπεν είναι το ψευδώνυμο για τη μεγάλη καμπάνα και το ρολόι στο βόρειο άκρο των ανακτόρων του Ουεστμίνστερ στο Λονδίνο , και έχει χρησιμοποιηθεί ευρύτερα ώστε να παραπέμπει γενικά στο ρολόι ή τον πύργο του ρολογιού. Είναι το μεγαλύτερο τεσσάρων όψεων ρολόι με καμπάνες και ο πύργος του ρολογιού είναι ο τρίτος ψηλότερος στον κόσμο. Γιόρτασε τα 150 χρόνια του στις 31 Μαΐου 2009, ημέρα κατά την οποία έλαβαν χώρα εορταστικές εκδηλώσεις. Η ανέγερση του πύργου ολοκληρώθηκε τις 10 Απριλίου [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gb {
            get {
                return ResourceManager.GetString("gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gb1 {
            get {
                object obj = ResourceManager.GetObject("gb1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gb2 {
            get {
                object obj = ResourceManager.GetObject("gb2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gb3 {
            get {
                object obj = ResourceManager.GetObject("gb3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gb4 {
            get {
                object obj = ResourceManager.GetObject("gb4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Γερμανία
        ///- Κάστρο Νοϊσβάνσταϊν -
        ///Το Κάστρο Νοϊσβάνσταϊν είναι παλάτι του 19ου αιώνα το οποίο βρίσκεται σε λόφο πάνω από το χωριό Σβάνγκαου κοντά στο Φύσεν στη νοτιοδυτική Βαυαρία στη Γερμανία. Η κατασκευή του διατάχθηκε από τον Λουδοβίκο Β΄ της Βαυαρίας ως χώρος ανάπαυσης και φόρος τιμής στον Ρίχαρντ Βάγκνερ. Ο Λουδοβίκος πλήρωσε για το παλάτι από τη περιουσία του και από δάνεια και όχι από τα δημόσια κεφάλαια της Βαυαρίας. Το παλάτι αρχικά σχεδιαζόταν να γίνει προσωπικό καταφύγιο του βασιλιά, αλλά άνοιξε [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ger {
            get {
                return ResourceManager.GetString("ger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ger1 {
            get {
                object obj = ResourceManager.GetObject("ger1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ger2 {
            get {
                object obj = ResourceManager.GetObject("ger2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ger3 {
            get {
                object obj = ResourceManager.GetObject("ger3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ger4 {
            get {
                object obj = ResourceManager.GetObject("ger4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ελλάδα
        ///-Παρθενώνας-
        ///Ο Παρθενώνας είναι ναός, χτισμένος προς τιμήν της θεάς Αθηνάς, προστάτιδας της πόλης της Αθήνας. Υπήρξε το αποτέλεσμα της συνεργασίας σημαντικών αρχιτεκτόνων και γλυπτών στα μέσα του 5ου π.Χ. αιώνα. Η εποχή της κατασκευής του συνταυτίζεται με τα φιλόδοξα επεκτατικά σχέδια της Αθήνας και της πολιτικής κύρους που ακολούθησε έναντι των συμμάχων της κατά την περίοδο της αθηναϊκής ηγεμονίας στην Αρχαία Ελλάδα.
        ///- Ναός του Ποσειδώνα-
        ///Σούνιο (ή Κάβο κολώνες ή Καβοκολώνες) ονομάζεται το ακρωτ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gr {
            get {
                return ResourceManager.GetString("gr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gr1 {
            get {
                object obj = ResourceManager.GetObject("gr1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gr2 {
            get {
                object obj = ResourceManager.GetObject("gr2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gr3 {
            get {
                object obj = ResourceManager.GetObject("gr3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gr4 {
            get {
                object obj = ResourceManager.GetObject("gr4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap im1 {
            get {
                object obj = ResourceManager.GetObject("im1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ιταλία
        ///- Κολοσσαίο-
        ///Το Κολοσσαίο άρχισε να κατασκευάζεται στην εποχή του Βεσπασιανού το 72 μ.Χ., συνεχίστηκε την εποχή του Τίτου και ολοκληρώθηκε όταν ήταν αυτοκράτορας ο Τίτος, το 80 μ.Χ. Ονομαζόταν Αμφιθέατρο των Φλαβίων, από το όνομα της δυναστείας των αυτοκρατόρων που το έκτισαν. Για να κατασκευαστεί, εργάστηκαν χιλιάδες Ιουδαίοι αιχμάλωτοι που είχαν συλληφθεί από τον Τίτο μετά την καταστροφή των Ιεροσολύμων. Πήρε το όνομά του από το κολοσσιαίο άγαλμα του Νέρωνα (Ο Κολοσσός), που βρισκόταν στην τοποθε [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap it1 {
            get {
                object obj = ResourceManager.GetObject("it1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap it2 {
            get {
                object obj = ResourceManager.GetObject("it2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap it3 {
            get {
                object obj = ResourceManager.GetObject("it3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap it4 {
            get {
                object obj = ResourceManager.GetObject("it4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ολλανδία-Το μουσείο της Άννα Φρανκ-Το Μουσείο της Άννας Φρανκ βρίσκεται στο υδάτινο κανάλι &quot;Πρίνσενχραχτ&quot; του Άμστερνταμ. Αποτελεί ένα βιογραφικό μουσείο, πάνω στη ζωή της Άννας Φρανκ, ενός μικρού κοριτσιού εβραϊκής καταγωγής, που έμεινε γνωστή μετά τον θάνατό της από το ημερολόγιό της, που διασώθηκε με τον τίτλο ’’Το ημερολόγιο της Άννας Φρανκ’’- Κεουκενχόφ-Μεγάλο πάρκο του 19ου αιώνα, ανοιχτό από τον Μάρτιο μέχρι τον Μάιο, με ολλανδικά ανοιξιάτικα λουλούδια.- A’ dam lookout- Το A&apos;DAM LOOKOUT είναι ένα κατ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ned {
            get {
                return ResourceManager.GetString("ned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ned1 {
            get {
                object obj = ResourceManager.GetObject("ned1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ned2 {
            get {
                object obj = ResourceManager.GetObject("ned2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ned3 {
            get {
                object obj = ResourceManager.GetObject("ned3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ned4 {
            get {
                object obj = ResourceManager.GetObject("ned4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ρουμανία-Κάστρο Μπραν-Το κάστρο  Μπραν (ρουμανικά: Castelul Bran) είναι κάστρο το οποίο βρίσκεται κοντά στο χωριό Μπραν, Κομητεία Μπρασόβ, στην κεντρική Ρουμανία. Το κάστρο κατασκευάστηκε τον 13ο αιώνα από το Τευτονικό Τάγμα και σήμερα αποτελεί εθνικό μνημείο της Ρουμανίας. Βρίσκεται στα όρια Τρανσυλβανίας και Βλαχίας. Συχνά αναφέρεται ως το «κάστρο του Κόμη Δράκουλα», αλλά δεν υπάρχουν στοιχεία ότι ο Μπραμ Στόκερ αναφερόταν σε αυτό το κάστρο και η σχέση του κάστρου με τον Βλαντ Γ΄ Τσέπες, έμπνευση του μυθι [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rom {
            get {
                return ResourceManager.GetString("rom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rom1 {
            get {
                object obj = ResourceManager.GetObject("rom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rom2 {
            get {
                object obj = ResourceManager.GetObject("rom2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rom3 {
            get {
                object obj = ResourceManager.GetObject("rom3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rom4 {
            get {
                object obj = ResourceManager.GetObject("rom4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ρωσία
        ///- Ερμιτάζ-
        ///Το Ερμιτάζ αποτελεί το μεγαλύτερο και ένα από τα παλαιότερα μουσεία στον κόσμο, καθώς και ένα από τα σημαντικότερα αξιοθέατα της Αγίας Πετρούπολης. Φιλοξενείται σε ένα συγκρότημα έξι κτιρίων, τα παλαιά Χειμερινά Ανάκτορα, στις όχθες του ποταμού Νέβα. Ανάμεσα στα σημαντικά εκθέματα του μουσείου, περιλαμβάνεται η συλλογή έργων δυτικοευρωπαϊκής τέχνης με έργα των Λεονάρντο ντα Βίντσι, Ωγκύστ Ροντέν, Πάμπλο Πικάσσο, Ανρί Ματίς, Πωλ Γκωγκέν, Πωλ Σεζάν, Κλωντ Μονέ, Ρέμπραντ και άλλων. Φιλοξενού [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rus {
            get {
                return ResourceManager.GetString("rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rus1 {
            get {
                object obj = ResourceManager.GetObject("rus1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rus2 {
            get {
                object obj = ResourceManager.GetObject("rus2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rus3 {
            get {
                object obj = ResourceManager.GetObject("rus3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rus4 {
            get {
                object obj = ResourceManager.GetObject("rus4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain info.
        /// </summary>
        internal static string s1 {
            get {
                return ResourceManager.GetString("s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ισπανία
        ///- Σαγράδα Φαμίλια-
        ///Η Σαγράδα Φαμίλια είναι μεγάλη ρωμαιοκαθολική εκκλησία στη Βαρκελώνη της Καταλονίας στην Ισπανία, σχεδιασμένη από τον Καταλανό αρχιτέκτονα Αντόνι Γκαουντί (1852 1926). Αν και ημιτελής, η εκκλησία αποτελεί Μνημείο Παγκόσμιας Κληρονομιάς της UNESCO[4] και το Νοέμβριο του 2010 εγκαινιάστηκε και καθαγιάστηκε από τον Πάπα Βενέδικτο ΙΣΤ΄ και έγινε Βασιλική και μπορεί πλέον να τελεστεί εκεί η Θεία Λειτουργία και να την παρακολουθήσουν οι πιστοί
        ///- Το Πάρκο Γκουέλ -
        ///Το Πάρκο Γκουέλ είν [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp {
            get {
                return ResourceManager.GetString("sp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sp1 {
            get {
                object obj = ResourceManager.GetObject("sp1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sp2 {
            get {
                object obj = ResourceManager.GetObject("sp2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sp3 {
            get {
                object obj = ResourceManager.GetObject("sp3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sp4 {
            get {
                object obj = ResourceManager.GetObject("sp4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σουηδία 
        ///- Ανάκτορο της Στοκχόλμης-
        ///Το παλάτι της Στοκχόλμης είναι η επίσημη κατοικία της σουηδικής βασιλικής οικογένειας και βρίσκεται στο ιστορικό κέντρο της πόλης (Gamla Stan) πολύ κοντά στην έδρα του σουηδικού κοινοβουλίου. Αρχικά στη θέση που βρίσκεται σήμερα το παλάτι υπήρχε μόνο το φρούριο που είχε χτιστεί τον 13ο αιώνα από τον Γιάρλ Μπίργκερ (Jarl Birger) και είχε σκοπό την υπεράσπιση του περάσματος προς τη λίμνη Μάλαρεν
        ///- Μουσείο Σκένσεν-
        ///Στην πανέμορφη Στοκχόλμη της Σουηδίας, στην περιοχή Djur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sw {
            get {
                return ResourceManager.GetString("sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sw1 {
            get {
                object obj = ResourceManager.GetObject("sw1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sw2 {
            get {
                object obj = ResourceManager.GetObject("sw2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sw3 {
            get {
                object obj = ResourceManager.GetObject("sw3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sw4 {
            get {
                object obj = ResourceManager.GetObject("sw4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test 1 
        ///ok.
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
    }
}
